# Generated by Django 4.1.4 on 2022-12-28 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='cate_name',
        ),
    ]
